### ISSUE TITLE
Server Error: Only variables should be passed by reference

### ISSUE THREAD

**Issue by benhaynes** [directus/static-generator#27]
I am getting this error when trying to generate code – do you know what it means?

**Comment by benhaynes** [comment]
Also getting this when trying to add a new file:

`/test/test.html`

**Comment by rijkvanzanten** [comment]
I also get this error when trying to create new files

**Comment by benhaynes** [comment]
This seems to be resolved for me now... (on save and new file). How about you @rijkvanzanten ?

**Comment by benhaynes** [comment]
Not getting this error anymore
