### ISSUE TITLE
Not getting Users index

### ISSUE THREAD

**Issue by benhaynes** [directus/static-generator#28]
Using the default code, I am not getting a `/Users` page generated despite the code saying:

`<!--- directus_route: /example/users ---> `

There IS a index to the `example` directory, but that doesn't even seems to be generated by the code (it never changes).

**Comment by rijkvanzanten** [comment]
This is working for me as expected on 510b99658369a906f49984ba1f982817bb8cc6cf

**Comment by benhaynes** [comment]
Looks good
