### ISSUE TITLE
Notification Timeout

### ISSUE THREAD

**Issue by benhaynes** [directus/static-generator#30]
Only error notifications should stay on the page, all other (blue) alerts should use the built-in timer to disappear after 1-2 seconds.

**Comment by benhaynes** [comment]
This has not been implemented for all notifications:

New File: `Request successfully processed.`

Please search for any others that haven't been updated too.

**Comment by benhaynes** [comment]
If it's easier, we can remove the "New File" notification since it should be obvious from the file appearing.

**Comment by benhaynes** [comment]
We can also remove the notification when you save a file – the asterisk disappearing is enough.

**Comment by jasekz** [comment]
I removed all 'success' notifications except for site generation since it displays the full path to the generated site.

**Comment by benhaynes** [comment]
Thank you...
