### ISSUE TITLE
Auto-save Code; save button for route only

### ISSUE THREAD

**Issue by benhaynes** [directus/static-generator#4]
Let's auto-save the code. If possible can we add a CSS class to the tab title when the code is changed (so I can style edited but unsaved tabs differently) and then remove the class when we auto-save?

We should save every few seconds, but only if the code has changed (not every keypress and not when nothing has changed). 

-----------

For the route we should make this "click to edit". The input can be read-only until a pencil/button is clicked... then it's editable with a save button.

**Comment by benhaynes** [comment]
I was going to open a separate ticket for this, but it should also be solved by this:

If you edit a page and then click to another tab/file for a second (eg: to check something), when you go back to the first file, any changes are lost (it reloads). This should be solved by auto-saving ... but it means we should also auto-save when changing tabs.

**Comment by benhaynes** [comment]
Still some issues here:

1. When it saves it resets the cursor position to the beginning of the file (which messes up the code if you're in the middle of typing). The editor also loses focus so you can't type at all.

2. Is there a way to avoid the whole screen having the smoke overlay when saving? It's quite distracting and blocks the editor if you're typing.

**Comment by benhaynes** [comment]
If we can't solve both of those then we should have an option to turn off auto-saving or just comment it out for now.

**Comment by jasekz** [comment]
I commented out the auto save for now.  #1 is due to re-rendering.  #2 appears to be triggered by Directus when calling the save method.

**Comment by benhaynes** [comment]
commenting out works for now...
